---

#- name: Add user 
#  hosts: all
#  tasks:

    - name: Include the list of users
      include_vars: ../vars/main.yml

    - name: Include the encrypted user passwords
      include_vars:  ../vars/vault

    - name: Add a new user with username and commentname who are defined in vars, if the account doesn't exist
      user:
        name: "{{ item.username }}"
        state: present
        comment: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
      with_items: "{{ users }}"
      when: users | length > 0
